name: Python CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.x
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        # Instala cualquier otra dependencia de tu proyecto si las tienes
        # pip install -r requirements.txt 
    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        exit-zero=$?
        if [ $exit-zero -ne 0 ]; then
          echo "Flake8 found issues."
          exit 1
        fi
    - name: Test with pytest
      run: |
        pytest